title: Deep Learning Reviews & Study
description: 보통 Detector에 관련된 논문을 리뷰합니다.
email: battery94@gist.ac.kr
google_analytics: UA-116226112-1
timezone: Asia/Seoul

repository: junjiwon1031/junjiwon1031.github.io
theme: jekyll-theme-slate

asset_urs: /assets

github:
  username: junjiwon1031
