title: Deep Learning Reviews & Study
email: battery94@gist.ac.kr
timezone: Asia/Seoul

repository: junjiwon1031/junjiwon1031.github.io
theme: jekyll-theme-slate

asset_urs: /assets

github:
  username: junjiwon1031
